cmake_minimum_required(VERSION 3.20)
# Project tags are uppercase-leading C++ identifiers stored as a YAML sequence.
file(STRINGS "${SETTINGS_FILE}" lines)
set(tags "")
set(reading_tags FALSE)
set(found_tags FALSE)
foreach(line IN LISTS lines)
    string(REGEX REPLACE "#.*$" "" line "${line}")
    if(line MATCHES "^tags:[ \t]*(.*)$")
        if(found_tags)
            message(FATAL_ERROR "Duplicate tags setting")
        endif()
        set(found_tags TRUE)
        set(reading_tags TRUE)
        string(STRIP "${CMAKE_MATCH_1}" inline_tags)
        if(inline_tags MATCHES "^\\[(.*)\\]$")
            string(REPLACE "," ";" tags "${CMAKE_MATCH_1}")
            set(reading_tags FALSE)
        elseif(NOT inline_tags STREQUAL "")
            message(FATAL_ERROR "Project tags must be a YAML sequence")
        endif()
    elseif(reading_tags)
        if(line MATCHES "^[ \t]*-[ \t]+(.+)$")
            list(APPEND tags "${CMAKE_MATCH_1}")
        elseif(line MATCHES "^[^ \t]")
            set(reading_tags FALSE)
        elseif(NOT line MATCHES "^[ \t]*$")
            message(FATAL_ERROR "Invalid project tag entry: ${line}")
        endif()
    endif()
endforeach()

set(enum_entries "    None = Canis::NoTag,\n")
set(cases "    case Tags::None: return \"\";\n")
set(seen "")
foreach(tag IN LISTS tags)
    string(STRIP "${tag}" tag)
    if(tag MATCHES "^\"(.*)\"$")
        set(tag "${CMAKE_MATCH_1}")
    elseif(tag MATCHES "^'(.*)'$")
        set(tag "${CMAKE_MATCH_1}")
    endif()
    if(NOT tag MATCHES "^[A-Z][A-Za-z0-9_]*$" OR tag MATCHES "__" OR tag STREQUAL "None")
        message(FATAL_ERROR "Invalid project tag '${tag}': use an uppercase-leading C++ identifier; None and __ are reserved")
    endif()
    if(tag IN_LIST seen)
        message(FATAL_ERROR "Duplicate project tag '${tag}'")
    endif()
    list(APPEND seen "${tag}")
    string(APPEND enum_entries "    ${tag} = Canis::TagIdFromName(\"${tag}\"),\n")
    string(APPEND cases "    case Tags::${tag}: return \"${tag}\";\n")
endforeach()

set(content "// Generated from project_settings/project.canis. Do not edit.\n#pragma once\n#include <string_view>\n#include <Canis/Tag.hpp>\n\nenum class Tags : Canis::TagId\n{\n${enum_entries}};\n\nconstexpr Canis::TagId ToTagId(Tags value) { return static_cast<Canis::TagId>(value); }\n\nconstexpr std::string_view ToTagName(Tags value)\n{\n    switch (value)\n    {\n${cases}    }\n    return {};\n}\n")
file(WRITE "${OUTPUT_FILE}.tmp" "${content}")
configure_file("${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}" COPYONLY)
file(REMOVE "${OUTPUT_FILE}.tmp")
